/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MenuFoldIcon: typeof import('tdesign-icons-vue-next')['MenuFoldIcon']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TAside: typeof import('tdesign-vue-next')['Aside']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCard: typeof import('tdesign-vue-next')['Card']
    TCheckbox: typeof import('tdesign-vue-next')['Checkbox']
    TConfigProvider: typeof import('tdesign-vue-next')['ConfigProvider']
    TContent: typeof import('tdesign-vue-next')['Content']
    TDrawer: typeof import('tdesign-vue-next')['Drawer']
    TForm: typeof import('tdesign-vue-next')['Form']
    TFormItem: typeof import('tdesign-vue-next')['FormItem']
    TIcon: typeof import('tdesign-vue-next')['Icon']
    TInput: typeof import('tdesign-vue-next')['Input']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TLink: typeof import('tdesign-vue-next')['Link']
    TMenu: typeof import('tdesign-vue-next')['Menu']
    TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
    TSpace: typeof import('tdesign-vue-next')['Space']
    TSubmenu: typeof import('tdesign-vue-next')['Submenu']
    TSwiper: typeof import('tdesign-vue-next')['Swiper']
    TSwiperItem: typeof import('tdesign-vue-next')['SwiperItem']
    TTypographyTitle: typeof import('tdesign-vue-next')['Title']
  }
}

// For TSX support
declare global {
  const MenuFoldIcon: typeof import('tdesign-icons-vue-next')['MenuFoldIcon']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const TAside: typeof import('tdesign-vue-next')['Aside']
  const TButton: typeof import('tdesign-vue-next')['Button']
  const TCard: typeof import('tdesign-vue-next')['Card']
  const TCheckbox: typeof import('tdesign-vue-next')['Checkbox']
  const TConfigProvider: typeof import('tdesign-vue-next')['ConfigProvider']
  const TContent: typeof import('tdesign-vue-next')['Content']
  const TDrawer: typeof import('tdesign-vue-next')['Drawer']
  const TForm: typeof import('tdesign-vue-next')['Form']
  const TFormItem: typeof import('tdesign-vue-next')['FormItem']
  const TIcon: typeof import('tdesign-vue-next')['Icon']
  const TInput: typeof import('tdesign-vue-next')['Input']
  const TLayout: typeof import('tdesign-vue-next')['Layout']
  const TLink: typeof import('tdesign-vue-next')['Link']
  const TMenu: typeof import('tdesign-vue-next')['Menu']
  const TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
  const TSpace: typeof import('tdesign-vue-next')['Space']
  const TSubmenu: typeof import('tdesign-vue-next')['Submenu']
  const TSwiper: typeof import('tdesign-vue-next')['Swiper']
  const TSwiperItem: typeof import('tdesign-vue-next')['SwiperItem']
  const TTypographyTitle: typeof import('tdesign-vue-next')['Title']
}