/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CodeIcon: typeof import('tdesign-icons-vue-next')['CodeIcon']
    CopyIcon: typeof import('tdesign-icons-vue-next')['CopyIcon']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TButton: typeof import('tdesign-vue-next')['Button']
    TSpace: typeof import('tdesign-vue-next')['Space']
  }
}

// For TSX support
declare global {
  const CodeIcon: typeof import('tdesign-icons-vue-next')['CodeIcon']
  const CopyIcon: typeof import('tdesign-icons-vue-next')['CopyIcon']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const TButton: typeof import('tdesign-vue-next')['Button']
  const TSpace: typeof import('tdesign-vue-next')['Space']
}