/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const MessagePlugin: typeof import('tdesign-vue-next').MessagePlugin
  const TCheckboxGroup: typeof import('tdesign-vue-next').CheckboxGroup
  const TRadioGroup: typeof import('tdesign-vue-next').RadioGroup
}
