/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChevronDownIcon: typeof import('tdesign-icons-vue-next')['ChevronDownIcon']
    ClearIcon: typeof import('tdesign-icons-vue-next')['ClearIcon']
    CodeIcon: typeof import('tdesign-icons-vue-next')['CodeIcon']
    CopyIcon: typeof import('tdesign-icons-vue-next')['CopyIcon']
    MoreIcon: typeof import('tdesign-icons-vue-next')['MoreIcon']
    RefreshIcon: typeof import('tdesign-icons-vue-next')['RefreshIcon']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchIcon: typeof import('tdesign-icons-vue-next')['SearchIcon']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCard: typeof import('tdesign-vue-next')['Card']
    TCheckboxGroup: typeof import('tdesign-vue-next')['CheckboxGroup']
    TDropdown: typeof import('tdesign-vue-next')['Dropdown']
    TDropdownItem: typeof import('tdesign-vue-next')['DropdownItem']
    TDropdownMenu: typeof import('tdesign-vue-next')['DropdownMenu']
    TInput: typeof import('tdesign-vue-next')['Input']
    TPopup: typeof import('tdesign-vue-next')['Popup']
    TRadioGroup: typeof import('tdesign-vue-next')['RadioGroup']
    TSpace: typeof import('tdesign-vue-next')['Space']
    TTag: typeof import('tdesign-vue-next')['Tag']
    TTooltip: typeof import('tdesign-vue-next')['Tooltip']
  }
}

// For TSX support
declare global {
  const ChevronDownIcon: typeof import('tdesign-icons-vue-next')['ChevronDownIcon']
  const ClearIcon: typeof import('tdesign-icons-vue-next')['ClearIcon']
  const CodeIcon: typeof import('tdesign-icons-vue-next')['CodeIcon']
  const CopyIcon: typeof import('tdesign-icons-vue-next')['CopyIcon']
  const MoreIcon: typeof import('tdesign-icons-vue-next')['MoreIcon']
  const RefreshIcon: typeof import('tdesign-icons-vue-next')['RefreshIcon']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SearchIcon: typeof import('tdesign-icons-vue-next')['SearchIcon']
  const TButton: typeof import('tdesign-vue-next')['Button']
  const TCard: typeof import('tdesign-vue-next')['Card']
  const TCheckboxGroup: typeof import('tdesign-vue-next')['CheckboxGroup']
  const TDropdown: typeof import('tdesign-vue-next')['Dropdown']
  const TDropdownItem: typeof import('tdesign-vue-next')['DropdownItem']
  const TDropdownMenu: typeof import('tdesign-vue-next')['DropdownMenu']
  const TInput: typeof import('tdesign-vue-next')['Input']
  const TPopup: typeof import('tdesign-vue-next')['Popup']
  const TRadioGroup: typeof import('tdesign-vue-next')['RadioGroup']
  const TSpace: typeof import('tdesign-vue-next')['Space']
  const TTag: typeof import('tdesign-vue-next')['Tag']
  const TTooltip: typeof import('tdesign-vue-next')['Tooltip']
}